#!/usr/bin/env bash
# Run cross-spectral analysis across tropics by iterating over tiles of 30deg
# longitude.

dir_work=/path/for/work/files
dir_out=/path/for/output/files
csagan_exe=/path/to/csagan.exe

for lon_west in {-180..150..30}
do
    for season in JJA MAM SON DJF
    do
	python csagan_multiprocess.py -e $csagan_exe -n 4 \
               -r tropics \
               -c $lon_west $((lon_west+30)) -35 35 \
               -s $season \
               -w $dir_work -o $dir_out 2>&1 | tee $dir_work/tropics_${season}_noswmask.txt

	python csagan_multiprocess.py -e $csagan_exe -n 4 \
               -r northern \
               -c $lon_west $((lon_west+30)) 25 65 \
               -s $season \
               -w $dir_work -o $dir_out 2>&1 | tee $dir_work/northern_${season}_noswmask.txt

	python csagan_multiprocess.py -e $csagan_exe -n 4 \
               -r southern \
               -c $lon_west $((lon_west+30)) -60 -25 \
               -s $season \
               -w $dir_work -o $dir_out 2>&1 | tee $dir_work/southern_${season}_noswmask.txt
    done
done

# Tidy a lingering output file from $csagan_exe.  There will have been multiple
# processes writing to this filename without thread safety, so its contents
# should be ignored.
rm -fv ./csaout-gain95.nc
